export PATH="$HOME/.fastlane/bin:$PATH"
export RANGER_LOAD_DEFAULT_RC='FALSE'

alias l="ls -G1l"
alias g="git"
alias nano='vi'
alias v='vi'
alias r='ranger'
alias gcl='git clone'
alias gc='git commit'
alias gp='git push'
alias gco='git checkout'
alias gA='git add -A'
alias ga='git add -nA'
alias gd='git diff'
alias amend='git commit --amend --no-edit'
alias bconf='vi ~/.bash_profile && source ~/.bash_profile'
alias vconf='vi ~/.vimrc'
alias r='ranger' 
alias bs='brew search'
alias bi='brew install'
